### ISSUE TITLE
Iphone 12 mobile rendering 

### ISSUE THREAD

**Issue by zaza81** [romboai/website-romboai#59]
Here

1)  there is the orange button event at the top of the page, there is no scroll up left. In case it's not difficult, otherwise we can keep
![IMG_2399](https://github.com/user-attachments/assets/d1dcefa6-e8d6-4ac5-b2f9-7dbdcf8fd868)

2) check content  margins 
![IMG_2400](https://github.com/user-attachments/assets/ad6e2cd4-a864-4e64-8b95-5e594dfb7bba)
![IMG_2402](https://github.com/user-attachments/assets/b1fa6bab-2776-436d-b65f-43bd011fa493)
![IMG_2404](https://github.com/user-attachments/assets/b1654ccd-b66d-4a93-af8c-8e93a80c0f24)

3) Title too big, change to smaller font
![IMG_2403](https://github.com/user-attachments/assets/e142b41d-f746-40db-9fe1-5bcd13ef0e71)

4) These logos are huge, maybe we can line 2 logos per row.
![IMG_2401](https://github.com/user-attachments/assets/9d98524b-3b1c-4850-87dc-3f9d3e522ee7)

5) is it possible to add this music to wave background video? Or play just for the homepage?

[sigla-superquark-aria-sulla-quarta-corda-made-with-Voicemod.mp3.zip](https://github.com/user-attachments/files/17174499/sigla-superquark-aria-sulla-quarta-corda-made-with-Voicemod.mp3.zip)

**Comment by Nillkabbo** [comment]
Fixed all the issues except point one. Because I am not clear what you wanted.
